spring:
  application:
    name: order-ms


  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  liquibase:
    change-log: db/changelog/master_db.yml
    # drop-first: true

  jpa:
    hibernate:
      ddl-auto: validate

redis:
  server:
    url: redis://localhost:6379

server:
  port: 8084


patient:
  service:
    url: http://localhost:8082/api/v1


test:
  service:
    url: http://localhost:8083/api/v1


#  evdeki tailscale serverim ucun
#patient:
#  service:
#    url: http://100.99.238.19:8082/api/v1
#test:
#  service:
#    url: http://100.99.238.19:8083/api/v1


